### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by marshallycheng** [marshallycheng/Gameshelf#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by s-pangburn** [comment]
- [x] This background should not scroll!
  - Another note, if you were to make it scroll, currently, the background jumps and starts over when you switch between login and signup. If you ever add scrolling in the future, this would not be acceptable.
- [x] Your nav buttons should highlight on hover in some way. You can recreate the rounded rectangle from Pinterest or darken the text, up to you.
- [x] Your nav logo should be just a smidge bigger. I think a height of 36 looks better (width set to auto)
- [x] Style your search bar so that the entire bar is highlighted when it is focused and not just the inner `<input>` field. Use the `::focus` css selector to accomplish this.
- [x] It won't do anything yet, but your nav logo should link to root
- [x] The profile navlink should probably be replaced with my username, to more closely mimic pinterest? I won't require this though, just a suggestion.

**Comment by s-pangburn** [comment]
- [x] This has to do with Heroku, but your wiki in this new repo doesn't link to your live site. I had to go to the old repo to find it
- [x] Opacity for your login dialog is a liiiittle too low. Just enough to make it a little hard to read with the moving background.
- [x] In the nav after you log in, your logo and your search need just a little bit of margin on the left and right to space everything out. It looks too cramped right now.

**Comment by s-pangburn** [comment]
Looks good Marshall! This MVP is finished! Feel free to move on completely to your next feature 👍
