### ISSUE TITLE
PA Review: Reviews

### ISSUE THREAD

**Issue by marshallycheng** [marshallycheng/Gameshelf#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by s-pangburn** [comment]
- [x] Edit Review button and Submit Review button should `cursor: pointer` on hover. 
- [x] If I click Edit Review the form clears (it shouldn't) and it doesn't switch back to the default text.
- [x] I can't edit or delete a review I just posted. I need to refresh the page first.
- [x] It's a little strange that the genres do `cursor: pointer` when they don't link anywhere. If you plan on adding categories by genre soon by all means keep it, otherwise remove it.
- [x] Your seed data needs a bit more review variety eventually. No need to do it right this second, but just as a note.

**Comment by s-pangburn** [comment]
Looks really good! Awesome job Marshall, this is looking to be pretty polished!
